name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      terraform_mode:
        description: "Select terraform operation"
        type: choice
        required: true
        default: 'terraform-plan'
        options:
          - 'terraform-plan'
          - 'terraform-apply'
          - 'terraform-plan for destroy'
          - 'terraform-destroy'
          
env:
  AWS_REGION: eu-west-3
  TERRAFORM_DIR: "./terraform"
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Print assumed role
      run: aws sts get-caller-identity

    - name: Check S3 buckets
      run: aws s3 ls
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform init
        
    - name: Terraform Plan
      if: ${{ inputs.terraform_mode == 'terraform_plan' }} || ${{ inputs.terraform_mode == 'terraform_apply' }}
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform plan

    - name: Terraform Apply
      if: ${{ inputs.terraform_mode == 'terraform_apply' }}
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform apply

    - name: Terraform Plan for destroy
      if: ${{ inputs.terraform_mode == 'terraform_plan for destroy' }} || ${{ inputs.terraform_mode == 'terraform_destroy' }}
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform plan -destroy
  
    - name: Terraform destroy
      if: ${{ inputs.terraform_mode == 'terraform_destroy' }}
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform destroy