name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      apply_changes:
        description: "Apply changes by executing 'terraform apply'?"
        type: choice
        required: true
        default: 'plan-only'
        options:
          - 'apply'
          - 'plan-only'
          
env:
  AWS_REGION: eu-west-3
  TERRAFORM_DIR: "./terraform"
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Print assumed role
      run: aws sts get-caller-identity

    - name: Check S3 buckets
      run: aws s3 ls
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform init
        
    - name: Terraform Plan
      run: |
        cd ${{ env.TERRAFORM_DIR }}
        terraform plan

    - name: Terraform Apply
      if: ${{ inputs.apply_changes == 'apply' }}
      run: |
          cd ${{ env.TERRAFORM_DIR }}
          echo "Terraform apply is currently blocked"
          # tterraform apply
