name: Publish post with REST API

on:
  workflow_dispatch:
    inputs:
      post_title:
        description: "Please enter the post's subject"
        required: true
        default: ''
      post_content:
        description: "Provide content of the post"
        required: true
        default: ''
          
env:
  AWS_REGION: eu-west-3
  TERRAFORM_DIR: "./terraform"
  SSH_KEYS_DIR: "./terraform/ssh_keys"
  
permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
          
    - name: Check Python installation and install requirements
      run: |
        python --version
        pip3 install -r ./python/requirements.txt

    - name: Run python script that will publish post
      run: python ./python/wp_api.py "${{ inputs.post_title }}" "${{ inputs.post_content }}"


      
